server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clothes-service
          uri: lb://clothes-service
          predicates:
            - Path=/api/v1/clothes/**
        - id: weather-service
          uri: lb://weather-service
          predicates:
            - Path=/api/v1/weather/**
      default-filters:
        - TokenRelay
  security:
    oauth2:
      client:
        provider:
          cw-keycloak-provider:
            issuer-uri: http://localhost:8764/auth/realms/cw-realm
        registration:
          keycloak-spring-gateway-client:
            provider: cw-keycloak-provider
            client-id: spring-gateway
            client-secret: XOvKyKcG8T5KOYYk9wQQpiSmlxG2voS9
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
management:
  endpoints:
    web:
      exposure:
        include: "*"