server:
  port: 8010
spring:
  application:
    name: weather-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://n.lvov:1705@localhost:27017/clothes_weather_db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8764/auth/realms/cw-realm/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9093
    topics:
      weather: cw-weather-process
webclient:
  weather:
    openweather:
      url: http://api.openweathermap.org/data/2.5/weather?units=metric&appid=${webclient.weather.openweather.appId}
      appId: 3de47b6f682cbdcb1c121ae491e0371d
springdoc:
  swagger-ui:
    servers:
      weather-service: lb://weather-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
