server:
  port: 8020
spring:
  application:
    name: clothes-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5433/clothes_weather_db
    username: n.lvov
    password: 1705
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8764/auth/realms/cw-realm/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9093
    topics:
      weather: cw-weather-process
springdoc:
  swagger-ui:
    servers:
      weather-service: lb://clothes-service
management:
  endpoints:
    web:
      exposure:
        include: "*"